name: cmp
description: Connected Music Player

version: 0.4.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #navigation
  nested_navigators:
    git:
      url: https://github.com/n0vah/nested_navigators.git

  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.13.4
  cloud_functions: ^0.4.2
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.0
  cupertino_icons: ^0.1.2
  html_unescape: ^1.0.1+3

  #song-player-stuff
  audioplayers: ^0.13.4

  media_notification_control: ^1.0.4
  youtube_player_flutter: ^6.0.3+2
  youtube_explode_dart: ^0.0.9

  http: ^0.12.0+1
  #youtube_api: ^0.7.2
  cached_network_image: ^2.0.0
  #flutter image picker
  image_picker: ^0.6.2

  dynamic_theme: ^1.0.1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  sembast: ^2.2.0
  provider: ^2.0.1
  package_info: ^0.4.0+14

  #qr-code
  open_file:
  wc_flutter_share: ^0.1.1
  barcode_scan: ^2.0.1
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1

  #icons
  flutter_launcher_icons: ^0.7.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path:
    "assets/icons/icon-blue-256x256.png"
    #flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/icons/icon-blue-256x256.png
    - assets/icons/soundcloud.png
    - assets/icons/youtube.png
    - assets/images/playlist.jpg
    - assets/images/plus.png
    - assets/images/user.svg
    - assets/images/default-user-avatar.png
    - assets/images/default-song-avatar.png
    - assets/images/default-playlist-avatar.jpg
    - assets/images/flags/germany.png
    - assets/images/flags/united-kingdom.png
    - assets/images/symbol_rot.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 600
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
