name: cmp
description: Connected Music Player

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #navigation
  nested_navigators:
    git:
      url: https://github.com/n0vah/nested_navigators.git
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  firebase_auth: ^0.15.0
  cupertino_icons: ^0.1.2
  html_unescape: ^1.0.1+3

  #song-player-stuff
  audioplayers: ^0.13.4
  #media_notification_control: ^1.0.4
  youtube_api: ^0.7.2
  #youtube_extractor: ^1.0.4
  youtube_player_flutter: ^6.0.3+2
  #flutter_youtube_extractor: ^0.0.7
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  #flutter image picker
  image_picker: ^0.6.2
  #image_cropper: ^1.2.1
  image_picker_saver: ^0.3.0
  dynamic_theme: ^1.0.1
  path_provider: ^1.4.4
  sembast: ^2.2.0
  shared_preferences: ^0.5.4+8
  barcode_scan: ^2.0.1
  open_file:

  #qr-code
  wc_flutter_share: ^0.1.1
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/images/playlist.jpg
    - assets/images/plus.png
    - assets/images/user.svg
    - assets/images/default-user-avatar.png
    - assets/images/default-song-avatar.png
    - assets/images/default-playlist-avatar.jpg
    - assets/images/flags/germany.png
    - assets/images/flags/united-kingdom.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 600
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
