class Language {
  String _appName = 'Connected-Music-Player';
  String _joinedPlaylists;

  Language(Map<String, dynamic> pNames) {
    this._joinedPlaylists = pNames['joined_playlists'];
  }

  //***************************************************//
  //*********   GETTER
  //***************************************************//
  String get appName => this._appName;
  String get joinedPlaylists => this._joinedPlaylists;
}

Language german = new Language({
  'joined_playlists': 'Beigetretene Playlists',
  'created_playlists': 'Erstellte Playlists',
  'actual_playlists': 'Aktuell beliebt',
  'all_playlists': 'Alle Playlists',
  'search_playlists': 'Playlist suchen',
  'create_playlist': 'Playlist erstellen',
  'edit_playlist': 'Playlist bearbeiten',
  'enter_playlist': 'Playlist eingeben',
  'name_of_playlist': 'Name der Playlist',
  'max_members': 'maximale Teilnehmeranzahl',
  'kind_of_playlist': 'Art der Playlist',
  'public': 'öffentliche Playlist',
  'private': 'private Playlist',
  'description': 'Beschreibung',
  'welcome': 'Willkommen',
  'welcome_back': 'Herzlich Willkommen',
  'to': 'bei',
  'cmp': 'CMP',
  'search': 'Suchen',
  'or': 'ODER',
  'create': 'Erstellen',
  'last_search': 'Letzte Suchanfragen',
  'delete_search': 'Suchverlauf löschen',
  'created_by': 'erstellt von ',
  'settings': 'Einstellungen',
  'show_profile': 'Profil anzeigen',
  'display_settings': 'Anzeigeeinstellungen',
  'language': 'Sprache',
  'profile': 'Profil',
  'username': 'Benutzername',
  'birthday': 'Geburtsdatum',
  'password': 'Passwort',
  'save_profile': 'Profil speichern',
  'queue': 'Warteschlange',
  'no_songs': 'Keine Songs vorhanden',
  'leave_playlist': 'Playlist verlassen',
  'delete_playlist': 'Playlist löschen',
  'show_code': 'QR-Code anzeigen',
  'search_song': 'Songs suchen',
  'enter_song': 'Song eingeben',
  'delete_song': 'Song entfernen',
  'information_to': 'Informationen zu ',
  'members': 'Teilnehmer',
  'requests': 'Anfragen',
  'visibilness': 'Sichtbarkeit',
  'actual_play': 'Aktuell läuft',
  'save': 'Speichern',
  'masterdevice_text': 'Es kann nur ein Masterdevice pro Playlist geben.',
});

Language english = new Language({
  'joined_playlists': 'Joined playlists',
  'created_playlists': 'Created playlists',
  'actual_playlists': 'Currently popular',
  'all_playlists': 'All playlists',
  'search_playlists': 'Search playlist',
  'create_playlist': 'Create playlist',
  'edit_playlist': 'Edit playlist',
  'enter_playlist': 'Enter a playlist',
  'name_of_playlist': 'Name of the playlist',
  'max_members': 'maximum number of members',
  'type_of_playlist': 'Type of playlist',
  'public': 'public playlist',
  'private': 'private playlist',
  'description': 'description',
  'welcome': 'Welcome',
  'welcome_back': 'Welcome back ',
  'to': 'to',
  'cmp': 'CMP',
  'search': 'Search',
  'or': 'OR',
  'create': 'Create',
  'last_search': 'Search history',
  'delete_search': 'Clear history',
  'created_by': 'created by ',
  'settings': 'Settings',
  'show_profile': 'Show profile',
  'display_settings': 'Displaysettings',
  'language': 'Language',
  'profile': 'Profile',
  'username': 'Username',
  'birthday': 'Birthday',
  'password': 'Password',
  'save_profile': 'Save profile',
  'queue': 'Queue',
  'no_songs': 'Keine Songs vorhanden',
  'leave_playlist': 'Leave playlist',
  'delete_playlist': 'Delete playlist',
  'show_code': 'Show QR-Code',
  'search_song': 'Search songs',
  'enter_song': 'Enter a Song',
  'delete_song': 'Delete song',
  'information_to': 'Informations to ',
  'members': 'Members',
  'requests': 'Requests',
  'visibilness': 'Visibilness',
  'actual_play': 'Currently playing',
  'save': 'Save',
  'masterdevice_text': 'There can only be one master device per playlist.',
});
