class Language {
  Map<String, String> _languagePack;

  Language(Map<String, String> pNames) {
    _languagePack = pNames;
  }

  //***************************************************//
  //*********   GETTER
  //***************************************************//
  Map<String, String> get languagePack => this._languagePack;

  String getLanguagePack(String pName) => this._languagePack[pName];
}

Language german = new Language({
  'joined_playlists': 'Beigetretene Playlists',
  'created_playlists': 'Erstellte Playlists',
  'actual_playlists': 'Aktuell beliebt',
  'all_playlists': 'Alle Playlists',
  'search_playlists': 'Playlist suchen',
  'create_playlist': 'Playlist erstellen',
  'edit_playlist': 'Playlist bearbeiten',
  'enter_playlist': 'Playlist eingeben',
  'name_of_playlist': 'Name der Playlist',
  'max_members': 'Maximale Teilnehmeranzahl',
  'type_of_playlist': 'Art der Playlist',
  'public': 'öffentliche Playlist',
  'private': 'private Playlist',
  'description': 'Beschreibung',
  'welcome': 'Willkommen',
  'welcome_back': 'Herzlich Willkommen',
  'to': 'bei',
  'cmp': 'CMP',
  'cmp_long': 'Connected Music Player',
  'search': 'Suchen',
  'or': 'ODER',
  'create': 'Erstellen',
  'last_search': 'Letzte Suchanfragen',
  'delete_search': 'Suchverlauf löschen',
  'created_by': 'Erstellt von ',
  'settings': 'Einstellungen',
  'show_profile': 'Profil anzeigen',
  'display_settings': 'Anzeigeeinstellungen',
  'language': 'Sprache',
  'logout': 'Abmelden',
  'profile': 'Profil',
  'username': 'Benutzername',
  'username_invalid': 'Geben Sie einen Benutzernamen ein!',
  'birthday': 'Geburtsdatum',
  'password': 'Passwort',
  'password_invalid': 'Geben Sie ein Passwort ein!',
  'save_profile': 'Profil speichern',
  'queue': 'Warteschlange',
  'no_songs': 'Keine Songs vorhanden',
  'by': ' von ',
  'leave_playlist': 'Playlist verlassen',
  'leave_playlist_text': 'Wollen Sie die Playlist wirklich verlassen?',
  'delete_playlist': 'Delete playlist',
  'delete_playlist_text': 'Wollen Sie die Playlist wirklich löschen?',
  'show_code': 'QR-Code anzeigen',
  'search_song': 'Songs suchen',
  'enter_song': 'Song eingeben',
  'delete_song': 'Song entfernen',
  'information_to': 'Informationen zu ',
  'members': 'Teilnehmer',
  'requests': 'Anfragen',
  'no_requests': 'Keine Anfragen vorhanden',
  'visibility': 'Sichtbarkeit',
  'actual_play': 'Aktuell läuft',
  'save': 'Speichern',
  'masterdevice_text': 'Es kann nur ein Masterdevice pro Playlist geben.',
  'yes': 'Ja',
  'no': 'Nein',
  'delete_user': 'Benutzer löschen',
  'user_deleted': 'Benutzer erfolgreich entfernt',
  'user_deleted_error': 'Benutzer kann nicht gelöscht werden, da dieser die Playlist erstellt hat',
  'join': 'Teilnehmen',
  'send_request': 'Anfrage senden',
  'request_sent': 'Anfrage gesendet',
  'to_playlist': 'Zur Playlist',
  'max_members_reached': 'Die maximale Anzahl an Teilnehmer wurde erreicht.',
  'full_playlist': 'Leider ist die Playlist bereits voll. \n Es tut uns sehr leid.',
  'played_from': 'Wiedergabe aus',
  'delete_profile': 'Profil löschen',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
  '': '',
});

Language english = new Language({
  'joined_playlists': 'Joined playlists',
  'created_playlists': 'Created playlists',
  'actual_playlists': 'Currently popular',
  'all_playlists': 'All playlists',
  'search_playlists': 'Search playlist',
  'create_playlist': 'Create playlist',
  'edit_playlist': 'Edit playlist',
  'enter_playlist': 'Enter a playlist',
  'name_of_playlist': 'Name of the playlist',
  'max_members': 'Maximum number of members',
  'type_of_playlist': 'Type of playlist',
  'public': 'public playlist',
  'private': 'private playlist',
  'description': 'Description',
  'welcome': 'Welcome',
  'welcome_back': 'Welcome back,',
  'to': 'to',
  'cmp': 'CMP',
  'cmp_long': 'Connected Music Player',
  'search': 'Search',
  'or': 'OR',
  'create': 'Create',
  'last_search': 'Search history',
  'delete_search': 'Clear history',
  'created_by': 'Created by ',
  'settings': 'Settings',
  'show_profile': 'Show profile',
  'display_settings': 'Displaysettings',
  'language': 'Language',
  'logout': 'Logout',
  'profile': 'Profile',
  'username': 'Username',
  'username_invalid': 'Enter a username!',
  'birthday': 'Birthday',
  'password': 'Password',
  'password_invalid': 'Enter a valid password!',
  'save_profile': 'Save profile',
  'queue': 'Queue',
  'no_songs': 'Keine Songs vorhanden',
  'by': ' of ',
  'leave_playlist': 'Leave playlist',
  'leave_playlist_text': 'Do you really want to leave the playlist?',
  'delete_playlist': 'Delete playlist',
  'delete_playlist_text': 'Do you really want to delete the playlist',
  'show_code': 'Show QR-Code',
  'search_song': 'Search songs',
  'enter_song': 'Enter a Song',
  'delete_song': 'Delete song',
  'information_to': 'Informations to ',
  'members': 'Members',
  'requests': 'Requests',
  'no_requests': 'No requests available',
  'visibility': 'Visibility',
  'actual_play': 'Currently playing',
  'save': 'Save',
  'masterdevice_text': 'There can only be one master device per playlist.',
  'yes': 'Ja',
  'no': 'Nein',
  'delete_user': 'Remove user',
  'user_deleted': 'User removed successfully',
  'user_deleted_error': 'User cannot be deleted because he created the playlist',
  'join': 'Join',
  'send_request': 'Send a request',
  'request_sent': 'Request sent',
  'to_playlist': 'to the Playlist',
  'max_members_reached': 'The maximum number of members has been reached.',
  'full_playlist': 'Unfortunately, the playlist is already full. \n We are very sorry.',
  'played_from': 'Music from',
});
