import 'package:cmp/models/language.dart';

Language english = new Language({
  'joined_playlists': 'Joined playlists',
  'created_playlists': 'Created playlists',
  'actual_playlists': 'Currently popular',
  'all_playlists': 'All playlists',
  'search_playlists': 'Search playlist',
  'create_playlist': 'Create playlist',
  'edit_playlist': 'Edit playlist',
  'enter_playlist': 'Enter a playlist',
  'name_of_playlist': 'Name of the playlist',
  'max_members': 'Maximum number of members',
  'type_of_playlist': 'Type of playlist',
  'public': 'public playlist',
  'private': 'private playlist',
  'description': 'Description',
  'welcome': 'Welcome',
  'welcome_back': 'Welcome back,',
  'to': 'to',
  'cmp': 'CMP',
  'cmp_long': 'Connected Music Player',
  'search': 'Search',
  'or': 'OR',
  'create': 'Create',
  'last_search': 'Search history',
  'delete_search': 'Clear history',
  'created_by': 'Created by ',
  'settings': 'Settings',
  'show_profile': 'Show profile',
  'display_settings': 'Display settings',
  'language': 'Language',
  'logout': 'Logout',
  'profile': 'Profile',
  'username': 'Username',
  'username_invalid': 'Enter a username!',
  'birthday': 'Birthday',
  'password': 'Password',
  'mail': 'Mail address',
  'password_invalid': 'Enter a valid password!',
  'save_profile': 'Save profile',
  'queue': 'Queue',
  'no_songs': 'Keine Songs vorhanden',
  'by': ' of ',
  'leave_playlist': 'Leave playlist',
  'leave_playlist_text': 'Do you really want to leave the playlist?',
  'delete_playlist': 'Delete playlist',
  'delete_playlist_text': 'Do you really want to delete the playlist',
  'show_code': 'Show QR-Code',
  'search_song': 'Search songs',
  'enter_song': 'Enter a Song',
  'delete_song': 'Delete song',
  'information_to': 'Informations to ',
  'members': 'Members',
  'requests': 'Requests',
  'no_requests': 'No requests available',
  'visibility': 'Visibility',
  'actual_play': 'Currently playing',
  'save': 'Save',
  'masterdevice_text': 'There can only be one master device per playlist.',
  'yes': 'Yes',
  'no': 'No',
  'delete_user': 'Remove user',
  'user_deleted': 'User removed successfully',
  'user_deleted_error': 'User cannot be deleted because he created the playlist',
  'join': 'Join',
  'send_request': 'Send a request',
  'request_sent': 'Request sent',
  'to_playlist': 'to the Playlist',
  'max_members_reached': 'The maximum number of members has been reached.',
  'full_playlist': 'Unfortunately, the playlist is already full. \n We are very sorry.',
  'played_from': 'Music from',
  'delete_profile': 'Delete profile',
  'change_darkmode': 'DarkMode is changed ...',
  'change_language': 'Language is changed ...',
  'load_playlist': 'Playlist is loading ...',
  'stop_playlist': 'The playlist has stopped!',
  'added_song': 'Your song will be added to ',
  'remove_user1': 'Are you sure you really want to remove ',
  'remove_user2': '?',
  'user_get_saved': 'User get saved ...',
  'saved_password': 'Password is saved!',
  'saved_user': 'Your profile is saved!',
  'wrong_values': 'Please check your inputs!',
  'delete_account': 'Delete account',
  'delete_account2': 'Do you really want to delete your account?',
  'delete_account_load': 'Your account get deleted ...',
  'account_deleted': 'Your account was successfully deleted!',
  'playlist_created': 'Your playlist created successfully!',
  'create_playlist_loading': 'Playlist is being created ...',
  'playlistname_invalid': 'Please enter a valid name!',
  'maxmembers_invalid': 'Please enter a number of members!',
  'description_invalid': 'Please enter a valid description!',
  'playlist_edited': 'Your playlist edited successfully!',
  'edit_playlist_loading': 'Playlist is being edited ...',
});
