import 'package:cmp/models/language.dart';

Language german = new Language({
  'joined_playlists': 'Beigetretene Playlists',
  'created_playlists': 'Erstellte Playlists',
  'actual_playlists': 'Aktuell beliebt',
  'all_playlists': 'Alle Playlists',
  'search_playlists': 'Playlist suchen',
  'create_playlist': 'Playlist erstellen',
  'edit_playlist': 'Playlist bearbeiten',
  'enter_playlist': 'Playlist eingeben',
  'name_of_playlist': 'Name der Playlist',
  'max_members': 'maximale Teilnehmeranzahl',
  'type_of_playlist': 'Art der Playlist',
  'public': 'öffentliche Playlist',
  'private': 'private Playlist',
  'description': 'Beschreibung',
  'welcome': 'Willkommen',
  'welcome_back': 'Herzlich Willkommen,',
  'to': 'bei',
  'cmp': 'CMP',
  'cmp_long': 'Connected Music Player',
  'search': 'Suchen',
  'or': 'ODER',
  'create': 'Erstellen',
  'last_search': 'Letzte Suchanfragen',
  'delete_search': 'Suchverlauf löschen',
  'created_by': 'Erstellt von ',
  'settings': 'Einstellungen',
  'show_profile': 'Profil anzeigen',
  'display_settings': 'Anzeigeeinstellungen',
  'language': 'Sprache',
  'logout': 'Abmelden',
  'profile': 'Profil',
  'username': 'Benutzername',
  'username_invalid': 'Geben Sie einen Benutzernamen ein!',
  'birthday': 'Geburtsdatum',
  'password': 'Passwort',
  'mail': 'E-Mail Adresse',
  'password_invalid': 'Geben Sie ein Passwort ein!',
  'save_profile': 'Profil speichern',
  'queue': 'Warteschlange',
  'no_songs': 'Keine Songs vorhanden',
  'by': ' von ',
  'leave_playlist': 'Playlist verlassen',
  'leave_playlist_text': 'Wollen Sie die Playlist wirklich verlassen?',
  'delete_playlist': 'Playlist löschen',
  'delete_playlist_text': 'Wollen Sie die Playlist wirklich löschen?',
  'show_code': 'Code anzeigen',
  'search_song': 'Songs suchen',
  'enter_song': 'Song eingeben',
  'delete_song': 'Song entfernen',
  'information_to': 'Informationen zu ',
  'members': 'Teilnehmer',
  'requests': 'Anfragen',
  'no_requests': 'Keine Anfragen vorhanden',
  'visibility': 'Sichtbarkeit',
  'actual_play': 'Aktuell läuft',
  'save': 'Speichern',
  'masterdevice_text': 'Es kann nur ein Masterdevice pro Playlist geben.',
  'yes': 'Ja',
  'no': 'Nein',
  'delete_user': 'Benutzer löschen',
  'user_deleted': 'Benutzer erfolgreich entfernt',
  'user_deleted_error': 'Benutzer kann nicht gelöscht werden, da dieser die Playlist erstellt hat',
  'join': 'Teilnehmen',
  'send_request': 'Anfrage senden',
  'request_sent': 'Anfrage gesendet',
  'to_playlist': 'Zur Playlist',
  'max_members_reached': 'Die maximale Anzahl an Teilnehmer wurde erreicht.',
  'full_playlist': 'Leider ist die Playlist bereits voll. \n Es tut uns sehr leid.',
  'played_from': 'Wiedergabe aus',
  'delete_profile': 'Profil löschen',
  'change_darkmode': 'DarkMode wird geändert ...',
  'change_language': 'Sprache wird geändert ...',
  'load_playlist': 'Playlist wird geladen ...',
  'stop_playlist': 'Die Playlist wurde angehalten!',
  'added_song': 'Dein Song wird hinzugefügt zu ',
  'remove_user1': 'Bist Du dir sicher, dass du ',
  'remove_user2': ' wirklich entfernen möchtest?',
  'user_get_saved': 'Benutzer wird gespeichert ...',
  'saved_password': 'Das Passwort wurde gespeichert!',
  'saved_user': 'Dein Profil wurde gespeichert!',
  'wrong_values': 'Bitte überprüfen Sie ihre Angaben!',
  'delete_account': 'Konto löschen',
  'delete_account2': 'Willst du dein Konto wirklich löschen?',
  'delete_account_load': 'Dein Konto wird gelöscht ...',
  'account_deleted': 'Dein Konto wurde erfolgreich gelöscht',
  'playlist_created': 'Ihre Playlist wurde erfolgreich erstellt!',
  'create_playlist_loading': 'Playlist wird erstellt ...',
  'playlistname_invalid': 'Geben Sie einen korrekten Namen ein!',
  'maxmembers_invalid': 'Geben Sie eine Teilnehmerzahl ein!',
  'description_invalid': 'Geben Sie eine korrekte Beschreibung ein!',
  'playlist_edited': 'Ihre Playlist wurde erfolgreich bearbeitet!',
  'edit_playlist_loading': 'Playlist wird bearbeitet ...',
});
